# Generated by Django 5.2.5 on 2025-10-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='id',
        ),
        migrations.RemoveField(
            model_name='games',
            name='reentry',
        ),
        migrations.AddField(
            model_name='games',
            name='game_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='games',
            name='reentry_buyin',
            field=models.CharField(blank=True, default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='games',
            name='buyin',
            field=models.CharField(blank=True, default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='games',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='games',
            name='time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
